### ISSUE TITLE
Add code coverage checks

### ISSUE THREAD

**Issue by kamathprasad9** [boscosylvester-john/se_hw_LuaToPython#3]
Automated code coverage checks using github actions to be implemented

**Comment by tusharkini** [comment]
I tried adding the coverage statistics to the repo and create a badge. Apparently only the repo owner can use codecov to create the badge and generate the coverage.
You can also use codacy if you want.

**Comment by tusharkini** [comment]
You need to use python module coverage by installing it in your system.  Use _$coverage run __init__.py_ inside of the tests folder to generate the coverage. Also you can see the coverage results by using _$ coverage results_. Currently the code coverage is around 73%. refer the documentation [here](https://coverage.readthedocs.io/en/6.5.0/)

**Comment by boscosylvester-john** [comment]
Code coverage added.
To execute code coverage run command "coverage report"
To generate html coverage report run command "coverage html"
Latest html coverage report has been placed under "htmlcov/index.html"
